server:
  port: 8202

spring:
  application:
    name: dt-user-service
  data:
    mongodb:
      username: dontrucker
      password: dontrucker
      database: dontruckerdb
      port: 27017
      host: dt-mongo-database

eureka:
  instance:
    preferUseIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://dt-discovery-service:8101/eureka


