spring:
  application:
    name: dt-offeritem-service

server:
  port: 8200

eureka:
  instance:
    preferUseIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://dt-discovery-service:8101/eureka
